### PR TITLE
translation review and implementation

### PR DESCRIPTION
**Pull request by MartaMalb**
I have quickly reviewed and implemented some typos in the following files: 
build.adoc
demos.adoc
depends.adoc
implementation.adoc

Happy to review more files in the future!

### CODE REVIEW

**Comment by stephengold** [comment]
Thank you Marta for your help. Currently I am waiting for @gattolfo98 to return from vacation. After that happens, I hope the two of you will work together.

**Comment by MartaMalb** [comment]
Hi @stephengold, no worries, we can wait for @gattolfo98 to be back. I'll be away for a couple of weeks myself, but I'll keep an eye on my inbox! Looking forward to working together! :)

**Review by gattolfo98 — APPROVED** [review]

**Comment by stephengold** [comment]
@gattolfo98: You ought to have the ability to merge this pull request. Do you?

**Comment by gattolfo98** [comment]
> @gattolfo98: You ought to have the ability to merge this pull request. Do you?

Yes, I was just waiting for your approval too

**Comment by stephengold** [comment]
That's very kind of you. In the future, however, please integrate PRs without waiting for my approval.

**Pull request merged**
